In [6]:
import numpy as np
np.random.seed(3)
val=np.random.randint(10,50,size=(3,5))
print(val)


[[34 13 18 10 31]
 [29 20 20 31 48]
 [42 30 39 49 24]]


In [7]:
val


array([[34, 13, 18, 10, 31],
       [29, 20, 20, 31, 48],
       [42, 30, 39, 49, 24]])

In [8]:
val[1:3,2:5]

array([[20, 31, 48],
       [39, 49, 24]])

In [9]:
val[:2,:2]

array([[34, 13],
       [29, 20]])

In [11]:
import numpy as np
np.random.seed(3)
mat1=np.random.randint(0,100,size=(9,9))
print(mat1)

[[24  3 56 72  0 21 19 74 41]
 [10 21 38 96 20 44 93 39 14]
 [26 81 90 22 66  2 63 60  1]
 [51 90 69 97 29 24 62  7 43]
 [33 79 48 37 20 94 49 21 78]
 [28 54  0 64 18 63 37 56 56]
 [71 37 46 33  1 85 74 99 91]
 [16 80 32 16 18 75 55 96 95]
 [13 37 30 48 61 33 52  2 28]]


In [ ]:
h=[2,4,5,6]
val=h.mean()
print(val)

AttributeError: 'list' object has no attribute 'np'

9
