In [7]:
import numpy as np
np.random.seed(5)
A = np.random.randint(0,100,size=(9,9))
print("Elements in matrix")
print(A)
B=[]

Elements in matrix
[[99 78 61 16 73  8 62 27 30]
 [80  7 76 15 53 80 27 44 77]
 [75 65 47 30 84 86 18  9 41]
 [62  1 82 16 78  5 58  0 80]
 [ 4 36 51 27 31  2 68 38 83]
 [19 18  7 30 62 11 67 65 55]
 [ 3 91 78 27 29 33 89 85  7]
 [16 94 14 90 31  9 38 47 16]
 [ 5 34 45 59 24 13 31 32 76]]


In [8]:
for i in range(0,A.shape[0],1):
  temp= A[0:].mean()
  B.append(temp)
print(B)

[43.7037037037037, 43.7037037037037, 43.7037037037037, 43.7037037037037, 43.7037037037037, 43.7037037037037, 43.7037037037037, 43.7037037037037, 43.7037037037037]


In [10]:
C=np.zeros((A.shape[0],A.shape[1]))
zerosCount=0
nonZerosCount=0
for i in range(0,A.shape[0]):
  for j in range(0,A.shape[1]):
    if A[i,j] > B[i]:
      C[i,j]=0
      zerosCount=zerosCount+1
    else :
      C[i,j]=A[i,j]
      nonZerosCount=nonZerosCount+1




In [11]:
if zerosCount+nonZerosCount==A.size:
  print("Updated matrix is validated")

else:
  print("Non validated")

print("Updated matrix")
print(C)
print("The numbner of zeros are:",zerosCount)
print("The numbner of Non-zeros are:",nonZerosCount)


Updated matrix is validated
Updated matrix
[[ 0.  0.  0. 16.  0.  8.  0. 27. 30.]
 [ 0.  7.  0. 15.  0.  0. 27.  0.  0.]
 [ 0.  0.  0. 30.  0.  0. 18.  9. 41.]
 [ 0.  1.  0. 16.  0.  5.  0.  0.  0.]
 [ 4. 36.  0. 27. 31.  2.  0. 38.  0.]
 [19. 18.  7. 30.  0. 11.  0.  0.  0.]
 [ 3.  0.  0. 27. 29. 33.  0.  0.  7.]
 [16.  0. 14.  0. 31.  9. 38.  0. 16.]
 [ 5. 34.  0.  0. 24. 13. 31. 32.  0.]]
The numbner of zeros are: 38
The numbner of Non-zeros are: 43


In [15]:
import  numpy as np
np.random.seed(3)
matrix=np.random.randint(0,50,size=(4,4),dtype=int)
print(matrix)

[[42 24  3  8]
 [ 0 21 19 10]
 [43 41 10 21]
 [38 32 20 44]]


In [16]:
matrix

array([[42, 24,  3,  8],
       [ 0, 21, 19, 10],
       [43, 41, 10, 21],
       [38, 32, 20, 44]])

In [18]:
rows,cols=matrix.shape
max_matrix=np.zeros((rows//2,cols//2),dtype=int)

In [21]:
for i in range(0,rows,2):
  for j in range(0,cols,2):
    submatrix = matrix[i:i+2,j:j+2]
    print(submatrix)
    temp=submatrix
    max_value=temp.max()
    print(f"Max value:{max_value}")
    print(temp)
    print()
    max_matrix[i//2,j//2]=max_value
print("Matrix of max values:")
print(max_matrix)

[[42 24]
 [ 0 21]]
Max value:42
[[42 24]
 [ 0 21]]

[[ 3  8]
 [19 10]]
Max value:19
[[ 3  8]
 [19 10]]

[[43 41]
 [38 32]]
Max value:43
[[43 41]
 [38 32]]

[[10 21]
 [20 44]]
Max value:44
[[10 21]
 [20 44]]

Matrix of max values:
[[42 19]
 [43 44]]
